# Generated by Django 5.0.2 on 2024-04-07 15:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director_de_programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('correo', models.CharField(max_length=500)),
                ('descripcion_cargo', models.TextField()),
                ('foto_de_perfil', models.ImageField(upload_to='fotosdirectores/')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField(default=30)),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('No Diponible', 'No Diponible')], default='Disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('salon', 'salon'), ('auditorio', 'auditorio'), ('coliseo', 'coliseo'), ('sala computo', 'sala computo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('lugar', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('creditos', models.IntegerField(default=1)),
                ('syllabus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=500)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('duracion_H', models.PositiveIntegerField(default=1)),
                ('orador', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('especializacion', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
                ('materias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_hora', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('salon_presencial', models.CharField(blank=True, max_length=50, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Programa_de_posgrado',
            fields=[
                ('name', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(default=datetime.date(2024, 3, 15))),
                ('fecha_finalizacion', models.DateField(default=datetime.date(2025, 3, 14))),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50)),
                ('duracion', models.PositiveIntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20)),
                ('facultad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Malla_curricular',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('requisitos_previos', models.TextField()),
                ('programa_de_posgrado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='programa_de_posgrado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado'),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('carreras', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_de_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(max_length=255)),
                ('tipo_de_servicio', models.CharField(max_length=255)),
                ('solicitante', models.CharField(max_length=50)),
                ('fecha_de_solicitud', models.DateField(verbose_name='')),
                ('decripcion', models.TextField()),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprovado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Viaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_viaje', models.DateField()),
                ('costo_de_viaje', models.DecimalField(decimal_places=2, default=2000000, max_digits=10)),
                ('invitados', models.IntegerField(default=10)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprovado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
    ]
