# Generated by Django 5.0.2 on 2024-03-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera_de_posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.BigIntegerField(default=0)),
                ('modalidad', models.TextField()),
                ('facultad', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
