# Generated by Django 5.0.2 on 2024-04-07 15:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director_de_programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_director', models.CharField(max_length=255)),
                ('numero_director', models.IntegerField()),
                ('correo_director', models.CharField(max_length=500)),
                ('foto_de_perfil', models.ImageField(upload_to='fotosdirectores/')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('espacio_codigo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacidad_espacio', models.IntegerField(default=30)),
                ('disponibilidad_espacio', models.CharField(choices=[('Disponible', 'Disponible'), ('No Diponible', 'No Diponible')], default='Disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('Salon', 'Salon'), ('Auditorio', 'Auditorio'), ('Coliseo', 'Coliseo'), ('Sala de Computo', 'Sala de Computo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nombre_evento', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_inicio_evento', models.DateField()),
                ('fecha_finalizacion_evento', models.DateField()),
                ('lugar_evento', models.TextField()),
                ('descripcion_evento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('codigo_facultad', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_facultad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre_materia', models.CharField(max_length=255)),
                ('codigo_materia', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('creditos_materia', models.IntegerField(default=1)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('nrc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_final_periodo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=255)),
                ('cedula', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(choices=[('Coordinador', 'Coordinador'), ('Gestor', 'Gestor'), ('Director de programa', 'Director de programa'), ('Lider', 'Lider')], max_length=255)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('nombre_actividad', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(max_length=255)),
                ('descripcion_actividad', models.TextField()),
                ('duracion_en_horas', models.PositiveIntegerField(default=1)),
                ('orador_actividad', models.CharField(max_length=255)),
                ('evento_actividad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre_profesor', models.CharField(max_length=255)),
                ('cedula_profesor', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('especializacion_profesor', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
                ('materias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_inicio_hora', models.DateTimeField()),
                ('fecha_final_hora', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('salon_presencial', models.CharField(blank=True, max_length=50, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Programa_de_posgrado',
            fields=[
                ('nombre_programa', models.CharField(max_length=255, unique=True)),
                ('codigo_programa', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fecha_inicio_programa', models.DateField(default=datetime.date(2024, 3, 15))),
                ('estado_programa', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50)),
                ('duracion_programa', models.PositiveIntegerField(default=1)),
                ('modalidad_programa', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20)),
                ('facultad_programa', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Malla_curricular',
            fields=[
                ('nombre_malla', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('requisitos_previos', models.TextField()),
                ('programa_de_posgrado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='programa_de_posgrado_evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado'),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_semestre', models.CharField(max_length=255)),
                ('estado_semestre', models.BooleanField(default=True)),
                ('carreras', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
                ('materias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud_de_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(max_length=255)),
                ('tipo_de_servicio', models.CharField(max_length=255)),
                ('solicitante', models.CharField(max_length=50)),
                ('fecha_de_solicitud', models.DateField(verbose_name='')),
                ('decripcion', models.TextField()),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Viaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_viatico', models.CharField(max_length=255)),
                ('destino_del_viatico', models.CharField(max_length=255)),
                ('fecha_inicio_viaje', models.DateField()),
                ('fecha_final_viaje', models.DateField()),
                ('costo_de_viaje', models.DecimalField(decimal_places=2, default=2000000, max_digits=10)),
                ('invitados_viatico', models.IntegerField(default=10)),
                ('estado_viatico', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento_viatico', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
    ]
