# Generated by Django 5.0.4 on 2024-04-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.CharField(default='000', max_length=3, primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
