# Generated by Django 5.0.3 on 2024-05-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='programa_de_posgrado',
            new_name='programa_de_posgrado_materia',
        ),
    ]
