# Generated by Django 5.0.4 on 2024-04-12 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='profesor',
        ),
        migrations.CreateModel(
            name='Nrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nrc', models.CharField(default=0, max_length=5, unique=True)),
                ('grupo', models.PositiveIntegerField(default=1)),
                ('materia_nrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
                ('periodo_nrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.periodo')),
            ],
        ),
    ]
