# Generated by Django 5.0.2 on 2024-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera_de_posgrado',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='carrera_de_posgrado',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='carrera_de_posgrado',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='carrera_de_posgrado',
            name='value',
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='carrera_de_posgrado',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
