# Generated by Django 5.0.4 on 2024-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionacademica',
            name='id_programacionAcademica',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
