# Generated by Django 5.0.3 on 2024-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id_horario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
