# Generated by Django 5.0.3 on 2024-04-28 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='fecha_final_horario',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
        ),
        migrations.AlterField(
            model_name='horario',
            name='fecha_inicio_horario',
            field=models.DateField(default=datetime.date(2024, 3, 15)),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_final_horario',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio_horario',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
