# Generated by Django 5.0.3 on 2024-04-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='nrc',
        ),
        migrations.AddField(
            model_name='horario',
            name='grupo',
            field=models.CharField(choices=[('001', '001'), ('002', '002'), ('003', '003'), ('004', '004')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia'),
        ),
    ]
