# Generated by Django 5.0.4 on 2024-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='año',
            field=models.IntegerField(default='2024'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='periodo',
            field=models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')], default='1'),
        ),
    ]
