# Generated by Django 5.0.4 on 2024-04-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_semestre_programa_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionacademica',
            name='semestre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.semestre'),
        ),
    ]
