# Generated by Django 5.0.4 on 2024-04-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_semestre_año_semestre_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='materias',
        ),
        migrations.AlterField(
            model_name='semestre',
            name='estado_semestre',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='periodo',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')], default='1'),
        ),
    ]
