# Generated by Django 5.0.4 on 2024-04-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_alter_materia_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionacademica',
            name='materia',
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='materia',
            field=models.ManyToManyField(to='CCSApp.materia'),
        ),
    ]
