# Generated by Django 5.0.3 on 2024-04-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_alter_horario_fecha_final_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='fecha_final_horario',
        ),
    ]
