# Generated by Django 5.0.2 on 2024-03-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_remove_carrera_de_posgrado_facultad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera_de_posgrado',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
