# Generated by Django 5.0.3 on 2024-04-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_remove_horario_nrc_horario_grupo_horario_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='tipo_actividad',
        ),
    ]
