# Generated by Django 5.0.3 on 2024-04-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0002_alter_horario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
