# Generated by Django 5.0.2 on 2024-03-03 21:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0003_alter_carrera_de_posgrado_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='duracion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='fecha_finalizacion',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2024, 3, 15)),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='value',
            field=models.DecimalField(decimal_places=2, default=2000000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrera_de_posgrado',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='carrera_de_posgrado',
            name='facultad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.facultad'),
        ),
    ]
