# Generated by Django 5.0.3 on 2024-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0003_alter_horario_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='codigo',
            new_name='cedula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
