# Generated by Django 5.0.3 on 2024-04-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0004_rename_codigo_usuario_cedula_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('nombre_edificio', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('numero_espacios', models.IntegerField()),
            ],
        ),
    ]
