# Generated by Django 5.0.3 on 2024-03-10 01:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0004_facultad_carrera_de_posgrado_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField(default=30)),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('No Diponible', 'No Diponible')], default='Disponible', max_length=20)),
                ('tipo', models.CharField(choices=[('salon', 'salon'), ('auditorio', 'auditorio'), ('coliseo', 'coliseo'), ('sala computo', 'sala computo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('lugar', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Malla_curricular',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('decripcion', models.TextField()),
                ('requisitos_previos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_de_posgrado',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('decripcion', models.TextField()),
                ('requisitos_previos', models.TextField()),
                ('creditos', models.IntegerField(default=1)),
                ('syllabus', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='facultad',
            name='id',
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('duracion_H', models.PositiveIntegerField(default=1)),
                ('orador', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('decripcion', models.TextField()),
                ('creditos', models.IntegerField(default=1)),
                ('syllabus', models.TextField()),
                ('malla_curricuala', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.malla_curricular')),
            ],
        ),
        migrations.AddField(
            model_name='malla_curricular',
            name='malla_curricular',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.modulo_de_posgrado'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('especializacion', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
                ('materias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Programa_de_posgrado',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField(default=datetime.date(2024, 3, 15))),
                ('fecha_finalizacion', models.DateField(default=datetime.date(2025, 3, 14))),
                ('value', models.DecimalField(decimal_places=2, default=2000000, max_digits=10)),
                ('duracion', models.PositiveIntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], default='Presencial', max_length=20)),
                ('facultad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='modulo_de_posgrado',
            name='programa_de_posgrado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='programa_de_posgrado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado'),
        ),
        migrations.CreateModel(
            name='Solicitud_de_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(max_length=255)),
                ('tipo_de_servicio', models.CharField(max_length=255)),
                ('solicitante', models.CharField(max_length=50)),
                ('fecha_de_solicitud', models.DateField(verbose_name='')),
                ('decripcion', models.TextField()),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprovado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('rol', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=500)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('telefono', models.IntegerField()),
                ('programa_de_posgrado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
            ],
        ),
        migrations.CreateModel(
            name='Viaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_viaje', models.DateField()),
                ('costo_de_viaje', models.DecimalField(decimal_places=2, default=2000000, max_digits=10)),
                ('invitados', models.IntegerField(default=10)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Aprobado', 'Aprovado'), ('Rechazado', 'Rechazado')], default='En curso', max_length=50)),
                ('evento', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.evento')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrera_de_posgrado',
        ),
    ]
