# Generated by Django 5.0.3 on 2024-04-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0004_remove_programacionacademica_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacionacademica',
            name='ciudad',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='cod_banner',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='correo_electronico',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='entrega_notas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='estado_de_contrato',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='fecha_de_clase',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='fecha_elab_contrato',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='horas',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='hotel',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='intu_canvas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='listas_mosaicos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='modalidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='num_contrato',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='telefono',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='tipo_de_contrato',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='tiquetes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='viaticos',
            field=models.CharField(default='', max_length=200),
        ),
    ]
