# Generated by Django 5.0.3 on 2024-04-29 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0004_remove_programacionacademica_modalidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='lugar_evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.espacio'),
        ),
    ]
