# Generated by Django 5.0.3 on 2024-03-17 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0005_espacio_evento_malla_curricular_modulo_de_posgrado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='programa_de_posgrado',
        ),
    ]
