# Generated by Django 5.0.4 on 2024-05-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0005_alter_horario_salon_presencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='salon_presencial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
