# Generated by Django 5.0.4 on 2024-05-03 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0003_remove_semestre_programa_semestre_and_more'),
        ('CCSApp', '0005_alter_horario_salon_presencial'),
    ]

    operations = [
    ]
