# Generated by Django 5.0.3 on 2024-05-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0005_alter_evento_lugar_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(default='', max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
