# Generated by Django 5.0.3 on 2024-03-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0005_espacio_evento_malla_curricular_modulo_de_posgrado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], max_length=20)),
                ('enlace_virtual', models.URLField(blank=True, null=True)),
                ('salon_presencial', models.CharField(blank=True, max_length=50, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.profesor')),
            ],
        ),
    ]