# Generated by Django 5.0.4 on 2024-05-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0006_alter_horario_salon_presencial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='salon_presencial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.espacio'),
        ),
    ]
