# Generated by Django 5.0.4 on 2024-04-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0006_remove_espacio_ubicacion_espacio_edificio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa_de_posgrado',
            old_name='name',
            new_name='nombre_programa',
        ),
        migrations.RemoveField(
            model_name='programa_de_posgrado',
            name='descripcion',
        ),
    ]
