# Generated by Django 5.0.3 on 2024-03-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0006_horario'),
        ('CCSApp', '0006_remove_usuario_programa_de_posgrado'),
    ]

    operations = [
    ]
