# Generated by Django 5.0.3 on 2024-05-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0006_merge_20240503_1711'),
        ('CCSApp', '0007_alter_horario_salon_presencial'),
    ]

    operations = [
    ]
