# Generated by Django 5.0.3 on 2024-03-19 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0007_merge_20240319_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malla_curricular',
            name='malla_curricular',
        ),
        migrations.AddField(
            model_name='malla_curricular',
            name='programa_de_posgrado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado'),
        ),
        migrations.DeleteModel(
            name='Modulo_de_posgrado',
        ),
    ]
