# Generated by Django 5.0.3 on 2024-05-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0008_merge_20240505_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_de_programa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
