# Generated by Django 5.0.2 on 2024-03-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0008_remove_malla_curricular_malla_curricular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director_de_programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('correo', models.CharField(max_length=500)),
                ('descripcion', models.TextField()),
                ('foto_de_perfil', models.ImageField(upload_to='fotosdirectores/')),
            ],
        ),
        migrations.RemoveField(
            model_name='programa_de_posgrado',
            name='value',
        ),
        migrations.AlterField(
            model_name='programa_de_posgrado',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], default='Presencial', max_length=20),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('carreras', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='CCSApp.programa_de_posgrado')),
            ],
        ),
    ]
