# Generated by Django 5.0.3 on 2024-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0008_merge_20240505_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_de_programa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], max_length=20),
        ),
    ]
