# Generated by Django 5.0.3 on 2024-03-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0008_remove_malla_curricular_malla_curricular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malla_curricular',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='decripcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='malla_curricuala',
        ),
    ]
