# Generated by Django 5.0.2 on 2024-03-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0009_director_de_programa_and_more'),
        ('CCSApp', '0009_rename_decripcion_malla_curricular_descripcion_and_more'),
    ]

    operations = [
    ]
