# Generated by Django 5.0.3 on 2024-05-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0009_alter_director_de_programa_id'),
        ('CCSApp', '0009_alter_director_de_programa_id_and_more'),
    ]

    operations = [
    ]
