# Generated by Django 5.0.3 on 2024-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0010_merge_20240505_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director_de_programa',
            name='numero_director',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=500),
        ),
    ]
