# Generated by Django 5.0.2 on 2024-03-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0010_merge_20240329_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director_de_programa',
            old_name='descripcion',
            new_name='descripcion_cargo',
        ),
    ]
