# Generated by Django 5.0.2 on 2024-03-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0011_rename_descripcion_director_de_programa_descripcion_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa_de_posgrado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
