# Generated by Django 5.0.3 on 2024-03-31 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0012_alter_horario_id'),
        ('CCSApp', '0012_programa_de_posgrado_estado'),
    ]

    operations = [
    ]
