# Generated by Django 5.0.3 on 2024-03-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0013_merge_20240331_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa_de_posgrado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=' ', max_length=50),
        ),
    ]
