# Generated by Django 5.0.3 on 2024-03-31 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0014_alter_programa_de_posgrado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='salon_presencial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCSApp.espacio'),
        ),
    ]
