# Generated by Django 5.0.3 on 2024-03-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0014_materia_programa_de_posgrado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='programa_de_posgrado',
            new_name='programa_posgrado',
        ),
    ]
