# Generated by Django 5.0.3 on 2024-03-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0015_rename_programa_de_posgrado_materia_programa_posgrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='programa_posgrado',
        ),
    ]
