# Generated by Django 5.0.2 on 2024-04-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0015_alter_horario_salon_presencial'),
        ('CCSApp', '0016_remove_materia_programa_posgrado'),
    ]

    operations = [
    ]
