# Generated by Django 5.0.2 on 2024-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCSApp', '0017_merge_20240331_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='salon_presencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='programa_de_posgrado',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=50),
        ),
    ]
